### ISSUE TITLE
Question about C# port

### ISSUE THREAD

**Issue by WoodsterDK** [Sonic-Amiga/opensdg-java#1]
Hi,

I have started to do a C# port - and have initially gotten the response to the TELL command, hence I try to respond with HELOPacket as described, but as soon as it is sent, the client is being disconnected.

I imagine the disconnect is due to a wrongly build HELO package - but I have tried a lot of different things, but simple cannot get it to work.
Would it be possible that you can generate a trace for a successfull connection, so I can try to back track what goes wrong?

Regards....

**Comment by Sonic-Amiga** [comment]
Hello! Nice to see you here.
Yes, you've built your HELO response in a wrong way. There's no error handling in the protocol, the remote instantly hangs up if it sees anything wrong.
 For HELO things are very simple. Let's look at the code:
```
            serverPubkey = new WELCPacket(pkt).getPeerID();
            logger.trace("Received server public key: {}", new Hexdump(serverPubkey));

            tempPubkey = new byte[SDG.KEY_SIZE];
            tempPrivkey = new byte[SDG.KEY_SIZE];
            curve25519xsalsa20poly1305.crypto_box_keypair(tempPubkey, tempPrivkey);
            logger.trace("Created short-term public key: {}", new Hexdump(tempPubkey));
            logger.trace("Created short-term secret key: {}", new Hexdump(tempPrivkey));

            sendPacket(new HELOPacket(serverPubkey, tempPubkey, tempPrivkey, getNextNonce()));
```
 So you need:
1. serverPubkey - this is a 32-byte (64 hex characters) string, also known as a peer ID
2. A corresponding pair of temporary keys (public and private)
3. Nonce. Nonces count from 0 and increment every packet. Note they have nothing to do with nonces other side uses (sometimes you will get them). Just monotonic increment. The other side is picky. If you violate the order, the remote will hang up. This can also be a catch when you start managing clients, which can make requests asynchronously. This is why sendData() method has a big lock inside.

Then we construct the packet as follows:
```
        public HELOPacket(byte[] serverPk, byte[] clientPk, byte[] clientSk, long nonce) throws ProtocolException {
            // This allocates "data" buffer of the required size and constructs header of our packet:
            // 2 bytes - packet size minus two (i. e. length of the following part)
            // 4 bytes - magic value of 0xf09f909f
            // 4 bytes - command AKA packet code
            // A possible catch: all multi-byte values are BIGENDIAN!!! I bet C# is little-endian internally.
            super(SDG.KEY_SIZE + SHORT_NONCE_SIZE + ZEROMSG_SIZE, CMD_HELO);

            // Next field in this packet - client private key (short-term) - 32 bytes
            data.put(clientPk);
            // Next goes nonce - 8 bytes
            data.putLong(nonce);

            // Now, according to the protocol, we derive a longer nonce for encryption. This is done
            // by simply prepending a fixed string (16 bytes) to our 8-byte nonce
            byte[] box_nonce = buildShortTermNonce("CurveCP-client-H", nonce);
            // Encrypted contents of our HELO message consists of zeroes. Note OUTER_PAD of 16 bytes.
            // This is original NaCL requirement to prefix all data with this pad. This pad is NOT ENCRYPTED
            // and is simply transferred to the encrypted message by the encryption function. In other words,
            // our actual payload to be encrypted is only ZEROMSG_SIZE bytes long; the resulting ciphertext
            // will also be prefixed by OUTER_PAD zeroes. I don't know why so.
            byte[] zeroMsg = new byte[OUTER_PAD + ZEROMSG_SIZE];

            // Encrypt in place, NaCl allows this
            // Unfortunately crypto_box API doesn't allow to specify starting offset
            // in the destination buffer, so we have to copy the result into our packet
            // Note that outer BOX_PAD is stripped and not sent
            encrypt(zeroMsg, zeroMsg, box_nonce, serverPk, clientSk);

            // This may be another catch. Pay attention to the phrase above. Initial OUTER_PAD is stripped from
            // the ciphertext; only the actual encrypted part is stored in the packet data buffer. The other side
            // will prepend this padding back for decryption.
            data.put(zeroMsg, OUTER_PAD, ZEROMSG_SIZE);
        }
```
 If you do everything correctly, it must work. If it still doesn't, make sure that you use the exact same CryptoBox algorithms. The original SDG library uses libsodium (https://doc.libsodium.org/), but the actual API comes from earlier NaCL library (https://nacl.cr.yp.to/). As far as i can understand, sodium considers that API deprecated and even doesn't document it, but that's what the original implementation uses. I think that you're using some native C# reimplementation. Make sure that it's compatible.

 Packet dumps won't really help you here. In fact while developing my Java reimplementation i had problems with pairing challenge-response; and that's how unit tests were written. Create a unit test with some hardcoded peerID and public key and dump the resulting encrypted data. Compare this with your C# implementation, it should produce the exact same thing. I compared against my first implementation in plain C.

**Comment by Sonic-Amiga** [comment]
If you really want to, you can make your own session dumps. Use my first research project for this: https://github.com/Sonic-Amiga/DEVIComm . It's a fork of original Trifork's demo repository with heavily modified demo app. UNIX build has ability to intercept decrypted packets and log them into a file. Supply "--dump <file_name>" command line option to activate the feature. The log is a human-readable hex dump. A "dumpreader" utility is also supplied, able to decode protobuf content from that.

**Comment by Sonic-Amiga** [comment]
Should you have more questions, don't hesitate to ask more. If you ask again, i will make some session dumps for you (it's 00:20AM here at the moment, so i am a bit sleepy, sorry). Or find my old ones from my Linux laptop. But there's really no more tricks to it; the whole thing is dead simple once you get the idea and don't mess up some numbers.

If Java code feels too much twisted, object-oriented and over-engineered, there's a C (yes, C, not C++) version: https://github.com/Sonic-Amiga/opensdg . It uses all the original APIs and original sodium library; and the internal design is a very dumb and straightforward. Can be a lot easier to read and transcribe. The file you need is tunnel_protocol.c. I basically wrote it by looking at IDA disassembly of the original lib.

**Comment by Sonic-Amiga** [comment]
One more  thing i can suggest is you share some code for review. Two pairs of eyes is better than one.

And one more. Once you advance further. Note that padding of 16 bytes is actually applied twice. I have already described OUTER_PADDING, which lives outside of the encrypted "box". There's also INNER_PADDING, which is always prepended to the payload to be encrypted; and contrary to OUTER_PADDING it's included in the encryption. So, ZEROMSG is actually 16 bytes of INNER_PADDING plus 64 bytes of actual "zero message". You'll see explicit use of INNER_PADDING in other packets.

Therefore, the actual data placement encryption structure looks as follows:
```
OUTER_PADDING 16 bytes <- Added prior to encryption/decryption, not transmitted over the wire
                    -----+
INNER_PADDING 16 bytes   | Encrypted content
Payload XXX bytes        |
                    -----+
```

**Comment by WoodsterDK** [comment]
Hi Sonic-Amiga,
thanks for a very elaborated response - much appreciated : )
I had issues getting your java version running, but actually this evening got it working, and can conclude, that it is the actual encryption that causes the issues - I'm using a port of libsodium, but somehow it encrypts different than your java version - so that is definitely the way to go....

Will try a few things, and get back....

Once again - thanks....

**Comment by Sonic-Amiga** [comment]
1. Check padding semantics. Your lib may handle them differently. For instance it could have omitted OUTER_PAD entirely. This would actually make things simpler for you.
2. Compare names of API functions you're using. Note that Java version uses "curve25519xsalsa20poly1305" family. I was able to come up with this by looking inside the original libsodium. Short names like "crypto_box_open()" wrap to similar long names inside. I am starting to remember that my pairing handshape bug was caused by typing "salsa" instead of "xsalsa", or something else instead of "25519"... Very easy to make such a mistake and ve-e-e-e-ry hard to spot it.
3. If nothing helps, compare actual library code. Eventually you'll understand what is what.

**Comment by Sonic-Amiga** [comment]
Java library should build well, it has Maven support and all the stuff. Testapp - yes, that's a very basic crude hack; i didn't want to spend a lot of time on it, only quickly put together very basic functions. It builds as standalone app referring to lib project. I didn't want to bother about maven build etc there since that's not really a distributable item.

**Comment by WoodsterDK** [comment]
I have been trying out different versions of encryption, but none seem to come to the same result at the java one.
NaCl has Curve25519XSalsa20Poly1305 implemented - but when comparing with output from java project, the encrypted message is different.
`            
byte[] cipher = new byte[m.Length + Curve25519XSalsa20Poly1305.TagLength];
            try
            {
                Curve25519XSalsa20Poly1305 box = new Curve25519XSalsa20Poly1305(sk, pk);

                box.Encrypt(cipher, m, n);
            }
            catch (Exception ex)
            {

            }
`

Sodium-core relies on libsodium but also gives something different than java version - BUT aggrees with NaCl
`
            byte[] data = Sodium.PublicKeyBox.Create(m, n, sk, pk);
`

Both adds 16byte tags, output are identical, but offset data at index 16 is different than java version

**Comment by Sonic-Amiga** [comment]
Hm, that's very interesting.

So, to sum things up, you've tried your C# sample code with two implementations of the crypto library: native C# port and wrapper on top of original sodium/nacl. And two implementations of the lib yield the same result, but my Java code yields a different one. Am i correct here ?

If yes, you've clearly messed up arguments. Cipher name looks correct.
Check that your nonce value is correct.
Check that what's supposed to be zero-initialized is indeed zero-initialized. Note that in Java new a[x] yields a zero-filled array. What about C#? Does it zero-fill the array or return uninitialized random contents ?
Check that you haven't swapped 'pk' and 'sk' around. It's damn easy to do because these are worst possible acronyms. Because you can read them both as:
Private Key vs Shared Key
and
Public Key vs Secret Key
beautiful, eh ?
If this still doesn't resolve your issue, i'd go the hard way. Single-step both samples in the debugger, side by side. Compare all the arguments and intermediate values. Eventually you'll smash your nose into the difference and it will immediately come crystal clear.

**Comment by Sonic-Amiga** [comment]
I have just pushed a new unit test to ease your task. It creates a HELOPacket using some static sample keys and dumps the final packet contents. Have fun.

**Comment by WoodsterDK** [comment]
Thanks for suggestions and help - apprecieated...

I have been breaking down the code, and trying test combinations of keys, to see if something has been switched around - but still no luck.

I tried to do printout to see where tings could go wrong - inputs seem to be ok and aligned - C# version adds mac, but offset data is still different.
Could it be endianess within libraries? 32 vs 64bit?

jnacl:
serverPubkey = 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
tempPubkey = caed7de0922801fe30c106502c3f562e6e9af6712172ca201c156fc5c82b0e1a
tempPrivkey = 529b3955d4ba7a76aef2d1f9acfe24d1abd771e70a5d8779646dbf6192329ed0
m = 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
n = 437572766543502d636c69656e742d480000000000000000
pk = 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
sk = 529b3955d4ba7a76aef2d1f9acfe24d1abd771e70a5d8779646dbf6192329ed0
c = 00000000000000000000000000000000cd045ebbc8d98a6567b555bf56bc4bc6baa9ff09b7ccfed01ce7a7ed85a04d8d3589c54d19a52c4ff678ccd4e86409c26de4623d86014df44cfae7b3dc002928d78b61191608cc1ea277f9e0dd7725de


NaCl:
serverPubkey = 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
tempPubkey = caed7de0922801fe30c106502c3f562e6e9af6712172ca201c156fc5c82b0e1a
tempPrivkey = 529b3955d4ba7a76aef2d1f9acfe24d1abd771e70a5d8779646dbf6192329ed0
m - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
n - 437572766543502d636c69656e742d480000000000000000
pk - 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
sk - 529b3955d4ba7a76aef2d1f9acfe24d1abd771e70a5d8779646dbf6192329ed0
c - 986b8de3a8bbd4329b3c284e228de913617fc9f53844fb5525cd4c81eb0c8ba07ecec51ebfe5e3f12543164fb18e577460c43176f1f6d9363bb636e2552aa75a374fddf42d657a584a260686242bf1f2231c5f87644f93721b0be989b863c2a6



NaCl - Reversed client public/secret:
serverPubkey = 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
tempPubkey = 529b3955d4ba7a76aef2d1f9acfe24d1abd771e70a5d8779646dbf6192329ed0
tempPrivkey = caed7de0922801fe30c106502c3f562e6e9af6712172ca201c156fc5c82b0e1a
m - 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
n - 437572766543502d636c69656e742d480000000000000000
pk - 97bf03fadd1dc842856368a44f84ea3b399f9a96c0bb2835be00c11d4934f495
sk - caed7de0922801fe30c106502c3f562e6e9af6712172ca201c156fc5c82b0e1a
c - c5a95f603ad7561131295a2189e6fd61d1a01f458aaad9256c9e2eb4a108bc07442bb7780b30f7d2b688d48698d1d643f2ea54070087a6e94f4b586d9f4955892197ffa720a39f80d1ec06329572f8647933e9771a325e0d510f7ad9c1acb73d

**Comment by Sonic-Amiga** [comment]
Hello! I have got some rest on weekend. Let's see, interesting...

**Comment by Sonic-Amiga** [comment]
So far, first of all i matched my ciphertext 'c' with your ciphertext:
```
mine:  00000000000000000000000000000000|cd045ebbc8d98a6567b555bf56bc4bc6baa9ff09b7ccfed01ce7a7ed85a04d8d3589c54d19a52c4ff678ccd4e86409c26de4623d86014df44cfae7b3dc002928d78b61191608cc1ea277f9e0dd7725de
yours: 986b8de3a8bbd4329b3c284e228de913|617fc9f53844fb5525cd4c81eb0c8ba07ecec51ebfe5e3f12543164fb18e577460c43176f1f6d9363bb636e2552aa75a374fddf42d657a584a260686242bf1f2231c5f87644f93721b0be989b863c2a6
```
 We immediately see two things:
1. Length match including INNER_PAD (16 bytes).
2. In my case inner pad is zero-filled (i separated it with vertical line), while in your case it's not. And, i guess, the first question is: why so ?

Java encryption function inside jnacl looks like:
```
	static public int crypto_secretbox(byte[] c, byte[] m, long mlen, byte[] n, byte[] k)
	{
                // 'k' is a result of crypto_box_beforenm()
		if (mlen < 32) // Make sure OUTER_PAD + INNER_PAD is present
			return -1;

		xsalsa20.crypto_stream_xor(c, m, mlen, n, k); // Magic
		poly1305.crypto_onetimeauth(c, 16, c, 32, mlen - 32, c); // More magic
		
		for (int i = 0; i < 16; ++i) // Zero out OUTER_PAD, don't leak onetimeauth key
			c[i] = 0;
		
		return 0;
	}
```
poly1305.crypto_onetimeauth() call reveals the real purpose of both pads:
OUTER_PAD serves as a temporary storage for a one-time key, used to build authentication data for the message (note 'c' as the last argument).
INNER_PAD serves as a storage for the authention tag, produced by the onetimeautH function(c, 16 as first and second arguments).
I guess that original C implementation doesn't allocate any extra bytes whatsoever; so all the storage, including temporary one, is supposed to be provided by the caller. Hence two pads inside the message. Java code simply replicates this behavior.
It's quite logical that OUTER_PAD is zeroed out afterwards, because otherwise it would leak security-critical stuff.
 So you first need to answer the question: why doesn't your ciphertext start with 16 zeroes ? Where's your OUTER_PAD ? You can do this by simply single-stepping inside the encryption function. I bet the answer is ve-e-e-ry simple. You're doing something wrong, just we don't see what. Maybe C# nacl has some different conventions. Maybe it doesn't want you to provide OUTER_PAD. I don't know, but you can see that by single-stepping.

**Comment by WoodsterDK** [comment]
Hi, 

I was thinking that since the lengths match up after the encryption, the C# library just added the MAC as default - will look into what happens.

For C# the message I think I tried to decode it based on encrypted message (without the MAC) and it works ok - but will double check later today....


According to example - it does not pad before doing the encryption
https://github.com/somdoron/NaCl.net

**Comment by Sonic-Amiga** [comment]
Hello!
 I have looked a little at source code and README for your library. It looks like your problem is that you have transcribed my code 1:1, but your library manages extra buffers itself.
1. You don't need OUTER_PAD at all.
2. Plaintext to encrypt also comes without INNER_PAD
```
// Plaintext message
// No INNER_PAD here!
byte[] message = Encoding.UTF8.GetBytes("Hey Bob");

// Prepare the buffer for the ciphertext, must be message length and extra 16 bytes for the authentication tag
// TagLength is the INNER_PAD
byte[] cipher = new byte[message.Length + Curve25519XSalsa20Poly1305.TagLength];

// Encrypting using alice box
// Note complete absence of OUTER_PAD
aliceBox.Encrypt(cipher, message, nonce);
```
 I think it's that simple.

**Comment by WoodsterDK** [comment]
Ok - I might be missing something very basic here, I have tried different things regarding sizes og input messages, and did take into account that library adds Tag but still the same. 

Would you be able just to generate the cipher in C# as well with the library?

**Comment by Sonic-Amiga** [comment]
Hello!
 I wrote a sample code and... Got a different result
I manage to figure out that a key value, computed during "box" creation, is different. This is Java code:
```
	public static int crypto_box_beforenm(byte[] k, byte[] pk, byte[] sk)
	{
		byte[] sp = new byte[32], sigmap = xsalsa20.sigma;
		
		curve25519.crypto_scalarmult(sp, sk, pk);
		return hsalsa20.crypto_core(k, null, sp, sigmap);
	}
```
And here is what C# does:
```
        public Curve25519XSalsa20Poly1305(ReadOnlySpan<byte> secretKey, ReadOnlySpan<byte> publicKey)
        {
            ReadOnlySpan<byte> input = stackalloc byte[16];
            Span<byte> span = stackalloc byte[32];
            Curve25519.ScalarMultiplication(span, secretKey, publicKey);
            HSalsa20.Transform(key, input, span, Span<byte>.Empty);
            span.Clear();
        }
```
 I instantly noticed difference in the second call parameters. Note that Java is using "sigma" value, while C# supplies Empty. I looked inside Transform:
 ```
            if (c.IsEmpty)
            {
                x0 = 0x61707865U;
                x5 = 0x3320646eU;
                x10 = 0x79622d32U;
                x15 = 0x6b206574U;
            }
 ```
  These hardcoded values in fact correspond to "sigma", so things are okay here.
 There are more differences in the code, but i need to be able to step through it in order to verify. Unfortunately my Visual Studio 2022 simply refuses to step into the library and/or set breakpoints there. I've done what https://www.michaelrinderle.com/2020/05/19/debugging-a-class-library-referenced-in-a-visual-studio-project/ suggests, but it didn't help. I can step inside standard libraries but not NaCL

**Comment by Sonic-Amiga** [comment]
I was able to work around by putting together a solution of two projects: my test code and NaCL.NET sources. And i was able to find out that result of the very first step, Curve25519.ScalarMultiplication(), is different. I compared the code against my working Java version; i see many differences, and i cannot tell which are equivalent and which are not because math has never been my strong side. I guess, if you really want to dig into that, you could talk to library's author.

So perhaps you have to throw this library away. In fact just typing 'NaCL' in NuGET package manager gives substantial number of alternatives. Try them, you should find what you need.

**Comment by WoodsterDK** [comment]
Hi, thanks for all you efforts.

I am a bit glad you get to the same conclusion than me, that something is off  - I actually tried to decode between a couple of C# libraries, and my initial thought is, that they are interchangeble..... will need to try a bit more.

If you should discover anything - please let me know :)
